#!/usr/bin/env python3
"""Collect merged PR release-note blocks since a git tag and format them as a
structured markdown release draft.

Usage:
  python3 scripts/release-notes.py                    # auto-detect last tag
  python3 scripts/release-notes.py --from-tag v1.0.0  # explicit start tag
  python3 scripts/release-notes.py --output notes.md  # write to file

Requirements: git, gh (GitHub CLI, authenticated)
"""

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from typing import Optional


# Category definitions: (key, display title, set of matching labels).
# Order = display order in the release draft.
CATEGORY_ORDER = [
    ("breaking",    "⚠️ Breaking Changes",  {"impact/breaking"}),
    ("security",    "🔒 Security",          {"impact/security"}),
    ("feature",     "✨ Features",           {"type/feature"}),
    ("fix",         "🐛 Bug Fixes",          {"type/fix"}),
    ("performance", "⚡ Performance",        {"type/performance"}),
    ("maintenance", "🔧 Maintenance",        {"type/chore", "type/refactor", "type/test", "type/docs"}),
]


@dataclass
class PR:
    number: int
    title: str
    labels: list
    body: str
    url: str
    merged_at: str

    def release_note(self) -> Optional[str]:
        """Extract the content of the ```release-note block from the PR body."""
        match = re.search(r"```release-note\s*\n(.*?)\n```", self.body or "", re.DOTALL)
        if not match:
            return None
        note = match.group(1).strip()
        if not note or note.upper() == "NONE":
            return None
        return note

    def skip(self) -> bool:
        return "skip-changelog" in self.labels


def _run(cmd: list) -> str:
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error running: {' '.join(cmd)}\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    return result.stdout.strip()


def last_tag() -> Optional[str]:
    result = subprocess.run(
        ["git", "describe", "--tags", "--abbrev=0"],
        capture_output=True,
        text=True,
    )
    return result.stdout.strip() if result.returncode == 0 else None


def tag_date(tag: str) -> str:
    """Return the ISO date (YYYY-MM-DD) of the commit a tag points at."""
    iso = _run(["git", "log", "-1", "--format=%aI", tag])
    # GitHub search only needs the date portion for merged:> queries.
    return iso[:10]


def fetch_prs(since_date: Optional[str]) -> list:
    search = "is:pr is:merged base:main"
    if since_date:
        search += f" merged:>{since_date}"

    raw = _run([
        "gh", "pr", "list",
        "--state", "merged",
        "--base", "main",
        "--search", search,
        "--json", "number,title,labels,body,url,mergedAt",
        "--limit", "500",
    ])
    data = json.loads(raw)
    prs = []
    for item in data:
        labels = [label["name"] for label in item.get("labels", [])]
        prs.append(PR(
            number=item["number"],
            title=item["title"],
            labels=labels,
            body=item.get("body") or "",
            url=item["url"],
            merged_at=item.get("mergedAt") or "",
        ))
    # Oldest-first so sections read chronologically.
    prs.sort(key=lambda p: p.merged_at)
    return prs


def categorize(prs: list) -> dict:
    """Assign each PR to exactly one category bucket (first match wins)."""
    buckets: dict = {key: [] for key, _, _ in CATEGORY_ORDER}
    buckets["uncategorized"] = []

    for pr in prs:
        if pr.skip():
            continue
        note = pr.release_note()
        placed = False
        for key, _, label_set in CATEGORY_ORDER:
            if label_set & set(pr.labels):
                buckets[key].append((pr, note))
                placed = True
                break
        if not placed:
            buckets["uncategorized"].append((pr, note))

    return buckets


def _format_entry(pr: PR, note: Optional[str]) -> list:
    """Return a list of markdown lines for one PR entry."""
    lines = []
    text = note if note else pr.title
    text_lines = text.splitlines()
    first = text_lines[0]
    rest = [l for l in text_lines[1:] if l.strip()]
    lines.append(f"- {first} ([#{pr.number}]({pr.url}))")
    for extra in rest:
        lines.append(f"  {extra}")
    return lines


def render(buckets: dict, from_tag: Optional[str], repo: str) -> str:
    lines = []

    tag_ref = from_tag or "(initial release)"
    lines.append(f"<!-- Generated by scripts/release-notes.py — review before publishing -->")
    lines.append(f"<!-- Range: {tag_ref} → HEAD -->")
    lines.append("")
    lines.append("## What's Changed")
    lines.append("")

    has_content = False
    for key, title, _ in CATEGORY_ORDER:
        entries = buckets.get(key, [])
        if not entries:
            continue
        has_content = True
        lines.append(f"### {title}")
        lines.append("")
        for pr, note in entries:
            lines.extend(_format_entry(pr, note))
        lines.append("")

    if not has_content:
        lines.append("_No user-facing changes in this release._")
        lines.append("")

    uncategorized = buckets.get("uncategorized", [])
    if uncategorized:
        lines.append("### Other")
        lines.append("")
        for pr, note in uncategorized:
            lines.extend(_format_entry(pr, note))
        lines.append("")

    if from_tag:
        lines.append("---")
        lines.append("")
        lines.append(
            f"**Full changelog**: https://github.com/{repo}/compare/{from_tag}...HEAD"
        )

    return "\n".join(lines)


def detect_repo() -> str:
    remote = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        capture_output=True,
        text=True,
    ).stdout.strip()
    slug = re.sub(r".*github\.com[:/]", "", remote)
    slug = re.sub(r"\.git$", "", slug)
    return slug


def main():
    parser = argparse.ArgumentParser(
        description="Generate a release note draft from merged PR release-note blocks."
    )
    parser.add_argument(
        "--from-tag",
        metavar="TAG",
        help="Collect PRs merged after this tag (default: last git tag).",
    )
    parser.add_argument(
        "--output",
        metavar="FILE",
        help="Write output to FILE instead of stdout.",
    )
    args = parser.parse_args()

    from_tag = args.from_tag or last_tag()
    since_date = None

    if from_tag:
        since_date = tag_date(from_tag)
        print(
            f"Collecting PRs merged after {from_tag} ({since_date})...",
            file=sys.stderr,
        )
    else:
        print("No previous tag found — collecting all merged PRs.", file=sys.stderr)

    repo = detect_repo()
    prs = fetch_prs(since_date)
    print(f"Found {len(prs)} merged PRs.", file=sys.stderr)

    buckets = categorize(prs)
    output = render(buckets, from_tag, repo)

    if args.output:
        with open(args.output, "w") as f:
            f.write(output)
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
