name: Build and Push

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  contents: read

jobs:
  build-server:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      context: .
      file: ./docker/Dockerfile.server
      platforms: linux/amd64,linux/arm64
      cache: true
      cache-scope: server
      meta-images: ghcr.io/${{ github.repository }}-server
      meta-tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-agent:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      context: .
      file: ./docker/Dockerfile.agent
      platforms: linux/amd64,linux/arm64
      cache: true
      cache-scope: agent
      meta-images: ghcr.io/${{ github.repository }}-agent
      meta-tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-agent-db:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      context: .
      file: ./docker/Dockerfile.agent-db
      platforms: linux/amd64,linux/arm64
      cache: true
      cache-scope: agent-db
      meta-images: ghcr.io/${{ github.repository }}-agent-db
      meta-tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
